const getInitialData = () => [
  {
    id: 1,
    company: "Photosnap",
    logo: "photosnap.svg",
    new: true,
    featured: true,
    position: "Senior Frontend Developer",
    postedAt: "1d ago",
    contract: "Full Time",
    location: "USA Only",
    languages: ["Frontend", "Senior", "HTML", "CSS", "JavaScript"],
    tools: [],
  },
  {
    id: 2,
    company: "Manage",
    logo: "manage.svg",
    new: true,
    featured: true,
    position: "Fullstack Developer",
    postedAt: "1d ago",
    contract: "Part Time",
    location: "Remote",
    languages: ["Fullstack", "Midweight", "Python"],
    tools: ["React"],
  },
  {
    id: 3,
    company: "Account",
    logo: "account.svg",
    new: true,
    featured: false,
    position: "Junior Frontend Developer",
    postedAt: "2d ago",
    contract: "Part Time",
    location: "USA Only",
    languages: ["Frontend", "Junior", "JavaScript"],
    tools: ["React", "Sass"],
  },
  {
    id: 4,
    company: "MyHome",
    logo: "myhome.svg",
    new: false,
    featured: false,
    position: "Junior Frontend Developer",
    postedAt: "5d ago",
    contract: "Contract",
    location: "USA Only",
    languages: ["Frontend", "Junior", "CSS", "JavaScript"],
    tools: [],
  },
  {
    id: 5,
    company: "Loop Studios",
    logo: "loop-studios.svg",
    new: false,
    featured: false,
    position: "Software Engineer",
    postedAt: "1w ago",
    contract: "Full Time",
    location: "Worldwide",
    languages: ["Fullstack", "Midweight", "JavaScript"],
    tools: ["Ruby", "Sass"],
  },
  {
    id: 6,
    company: "FaceIt",
    logo: "faceit.svg",
    new: false,
    featured: false,
    position: "Junior Backend Developer",
    postedAt: "2w ago",
    contract: "Full Time",
    location: "UK Only",
    languages: ["Backend", "Junior", "Ruby"],
    tools: ["RoR"],
  },
  {
    id: 7,
    company: "Shortly",
    logo: "shortly.svg",
    new: false,
    featured: false,
    position: "Junior Developer",
    postedAt: "2w ago",
    contract: "Full Time",
    location: "Worldwide",
    languages: ["Frontend", "Junior", "HTML", "JavaScript"],
    tools: ["Sass"],
  },
  {
    id: 8,
    company: "Insure",
    logo: "insure.svg",
    new: false,
    featured: false,
    position: "Junior Frontend Developer",
    postedAt: "2w ago",
    contract: "Full Time",
    location: "USA Only",
    languages: ["Frontend", "Junior", "JavaScript"],
    tools: ["Vue", "Sass"],
  },
  {
    id: 9,
    company: "Eyecam Co.",
    logo: "eyecam-co.svg",
    new: false,
    featured: false,
    position: "Full Stack Engineer",
    postedAt: "3w ago",
    contract: "Full Time",
    location: "Worldwide",
    languages: ["Fullstack", "Midweight", "JavaScript", "Python"],
    tools: ["Django"],
  },
  {
    id: 10,
    company: "The Air Filter Company",
    logo: "the-air-filter-company.svg",
    new: false,
    featured: false,
    position: "Front-end Dev",
    postedAt: "1mo ago",
    contract: "Part Time",
    location: "Worldwide",
    languages: ["Frontend", "Junior", "JavaScript"],
    tools: ["React", "Sass"],
  },
];

export { getInitialData };
